# Set the source folder (where your content files are)
source: src

# Set the destination folder (where Jekyll will generate the site)
destination: dist

# Optional: You can set a theme if needed (remove if not using one)
theme: jekyll-theme-primer

# Optional: Plugins you might want to use (you can customize this list)
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-coffeescript

# Optional: Exclude files or folders you don't want Jekyll to process
exclude:
  - "README.md"
  - "LICENSE"
  - "node_modules"
