name: GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Or any other build tools you're using

      - name: Build the site
        run: npm run build  # Adjust if you're using Vite or another build tool

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_branch: gh-pages  # Use 'gh-pages' for GitHub Pages deployment
          folder: dist  # Folder containing the built site (e.g., 'dist' for Vite)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the secret in the environment variable
