name: GitHub Pages

on:
  push:
    branches:
      - master  # Change from 'main' to 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Or any other build tools you're using

      - name: Build the site
        run: npm run build  # Or adjust if you're using Vite or another build tool

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_branch: master  # Change from 'gh-pages' to 'master'
          folder: dist  # Adjust to the folder where your build output goes
